//Lazy loading is a technique where components not required on the homepage can be split into seperate code bundles and downloaded only when user navigates to that page (Incrementally downloading application)
//It helps reduce initial loadtime thereby improving performance.
//we need react suspence and dynamic export to lazyload the route
//dynamic loading requires the const exported by default
//
const About =()=>{
    return(
        <div>

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis luctus, arcu sit amet sagittis mattis, odio augue mattis purus, ut sollicitudin eros elit sed nunc. Integer rhoncus nisi volutpat, feugiat eros a, laoreet nunc. Suspendisse feugiat tellus enim, et rutrum lacus eleifend eget. Mauris hendrerit bibendum accumsan. Aliquam massa nisi, convallis iaculis lectus et, placerat venenatis tellus. Vestibulum quis ligula tellus. Vestibulum sed blandit magna. Morbi a mauris sit amet ex fermentum porttitor at ut eros. Curabitur tincidunt diam vitae sapien sollicitudin auctor. Nunc viverra ante dapibus rhoncus venenatis. Nullam suscipit ante at dui fringilla eleifend. Phasellus bibendum et orci at mollis.

        Cras semper nulla ut dolor commodo pellentesque. Nunc vel massa bibendum, pretium odio eu, ornare urna. Nunc tincidunt luctus massa, non facilisis ipsum pellentesque vitae. Suspendisse bibendum tempus ornare. Maecenas augue sapien, efficitur non urna sit amet, porta fringilla libero. Donec mollis justo tortor, non egestas metus interdum eget. Praesent euismod scelerisque sapien, vel pulvinar mauris accumsan nec. Ut at luctus odio. Donec nec porttitor sapien. Nunc urna orci, gravida a elit at, pulvinar aliquam risus. Nullam blandit arcu ut dictum egestas. Cras sollicitudin quam nisl, posuere viverra justo vehicula in.

        Cras a turpis vel est malesuada mollis vitae quis nisi. Aliquam vel tortor libero. Nam fringilla nunc non tellus venenatis hendrerit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi eleifend iaculis nisi ac aliquet. Phasellus egestas lacus ac ligula pulvinar, id lacinia velit malesuada. Pellentesque vitae commodo mauris, quis sagittis dui. Cras sodales elit turpis, vel congue metus viverra sit amet. Quisque vestibulum quis mi eu commodo.

        In in augue et lorem tempus vulputate. Sed tempor, ligula lacinia aliquet facilisis, sem odio ultrices nisi, vel mattis turpis nisl bibendum ex. Nullam pulvinar neque sit amet cursus viverra. Cras dignissim odio vel molestie porttitor. Quisque varius leo sit amet augue aliquet consectetur. Cras ipsum lectus, pulvinar quis tellus at, convallis blandit massa. Nullam porta eleifend mauris ac tempus.

        Nulla facilisis ipsum tristique lacinia malesuada. Etiam ligula justo, bibendum sed libero ut, consectetur imperdiet tortor. Maecenas nec lacus a ipsum lacinia ornare. Curabitur eget est vel sem lacinia volutpat vel sit amet quam. Phasellus tincidunt molestie volutpat. Nunc blandit erat id sodales imperdiet. Donec sit amet elit dolor. Etiam eget sem id metus elementum finibus sit amet nec elit. Vestibulum laoreet consequat augue, a consectetur urna malesuada dignissim. Pellentesque magna sem, ullamcorper at diam ac, aliquam molestie turpis. Morbi venenatis velit in nunc sodales, eget ornare nisl fringilla. Vivamus molestie tempus quam eget dictum. Ut vitae ex eget turpis ultrices iaculis.

        Sed urna orci, ornare sed ex vel, rhoncus faucibus augue. Nunc mauris nisi, volutpat ac ullamcorper quis, tristique a velit. Aenean fermentum eu ex vitae congue. Nulla in auctor elit. Suspendisse potenti. Donec vehicula justo ante, a porta erat imperdiet at. Vestibulum ultrices tellus nec aliquet tempor. Integer egestas lobortis est id egestas. Donec hendrerit lorem id sapien rhoncus, nec facilisis arcu pharetra. Nam interdum malesuada venenatis. Nullam non metus fermentum, faucibus lectus sed, mollis sem. Donec commodo ante vel ex iaculis, sit amet congue augue facilisis. Ut sollicitudin condimentum felis, et venenatis urna congue quis. Fusce ornare, nulla eu scelerisque lacinia, enim eros ultrices sapien, at aliquam urna ante ac ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Praesent eget velit non augue feugiat interdum quis vel est. Integer pulvinar ipsum vel est malesuada, id feugiat nunc consectetur. Morbi in quam est. Nam ut mollis dolor. Praesent nec sem ultricies, luctus mauris at, lacinia nunc. Maecenas tempus commodo blandit. Nullam sodales urna vitae justo varius, nec euismod ipsum iaculis. Duis egestas, lectus ut semper ornare, enim augue sagittis nulla, volutpat sagittis dolor mi quis mi. Proin ultrices justo leo.

        Integer et arcu bibendum sem aliquam sagittis id eget sapien. Nam sit amet nisi accumsan nibh ultrices pharetra eget vitae arcu. Vestibulum pulvinar ex dolor, sit amet finibus ante pellentesque in. Curabitur bibendum mauris id imperdiet laoreet. Maecenas fermentum risus aliquam neque efficitur hendrerit quis vel ligula. Pellentesque id condimentum neque, eu finibus dolor. Aliquam aliquet luctus consectetur.

        In hac habitasse platea dictumst. Quisque ornare molestie mattis. Sed diam nunc, mollis eget massa vel, fringilla pellentesque lectus. Sed egestas tempus mollis. Curabitur blandit orci eget est imperdiet dictum. Etiam porttitor velit lectus, et scelerisque quam convallis ut. Vivamus turpis tellus, gravida sit amet efficitur eget, blandit id lectus. Mauris malesuada sapien eget nisl rutrum, nec efficitur eros rhoncus. Vivamus risus nisi, sollicitudin sed feugiat sed, condimentum id sem. Duis id purus nec dolor volutpat placerat nec malesuada libero. Quisque tincidunt nulla ipsum, ut dignissim metus varius mattis. Sed fringilla id nibh vitae elementum. Nullam non massa elementum, cursus eros at, mollis ex. Phasellus congue faucibus nisi, et aliquet sem viverra ut. In quis justo nec neque euismod dignissim quis et nisl. Praesent scelerisque dignissim arcu.

        Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer iaculis quam vel magna mattis, eleifend scelerisque mauris aliquet. Proin ac est leo. Quisque a metus tincidunt, aliquam mi vitae, finibus turpis. Nunc efficitur felis molestie viverra iaculis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam vitae ipsum urna. In nec ante ac leo tristique aliquet. Praesent gravida enim a felis commodo porta. Curabitur vitae purus mi.

        Nullam auctor nisi orci, vitae ultricies justo ornare aliquam. Quisque diam leo, malesuada sit amet condimentum eget, tristique vel urna. Phasellus orci urna, gravida ut dignissim id, blandit at purus. Integer lectus nunc, luctus eu posuere in, lacinia vel ante. Ut turpis tortor, feugiat sed ullamcorper ac, volutpat nec odio. Sed faucibus consequat elit eget luctus. Donec hendrerit tempus leo, at lobortis nisi placerat euismod. Proin sodales eget diam eu dapibus. Nam eget lorem posuere, pharetra erat et, luctus sem. Etiam a efficitur lectus, id imperdiet felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

        Fusce sollicitudin finibus tellus quis elementum. Aliquam erat volutpat. Cras convallis, mi at placerat pretium, nunc augue faucibus dolor, vel sagittis magna velit a eros. Duis quis finibus sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla rutrum, elit ac gravida ullamcorper, justo nunc imperdiet lorem, a vehicula sem elit ac metus. Etiam id molestie ipsum, eget tempus tortor. Morbi at venenatis nunc, quis cursus orci. Quisque pulvinar elit vel nisl lobortis aliquam. Duis eleifend scelerisque pharetra. Quisque finibus, ex non aliquam dictum, augue libero aliquam orci, vitae sodales massa nisl eu dui. Sed rhoncus non ante sed pretium. Duis et commodo risus. Vivamus volutpat, massa a luctus mollis, massa velit imperdiet lorem, quis venenatis erat lorem a sem. Nullam mollis facilisis sapien, a tempor eros congue vel. Morbi vel magna sit amet mauris fermentum dapibus.

        Praesent quam erat, vehicula at neque in, iaculis vehicula sem. Proin placerat sed augue sit amet laoreet. Duis commodo, libero sit amet viverra volutpat, libero urna fringilla nunc, id posuere lectus ipsum ut sem. Aliquam et eros libero. Suspendisse mi tortor, consequat ullamcorper turpis pulvinar, consequat faucibus ligula. Vestibulum in ex eget odio faucibus molestie eu in orci. Sed non nisl dignissim, tempus ex imperdiet, dictum sapien. Nullam blandit, sem non blandit rhoncus, quam sapien fringilla purus, quis vestibulum eros elit in nunc. In hac habitasse platea dictumst.

        Etiam quis metus dapibus, blandit odio sit amet, congue lacus. Praesent odio purus, interdum in turpis id, egestas sagittis mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut id sapien in risus faucibus sagittis id in lacus. Donec diam leo, vulputate sed ligula vel, fringilla pellentesque augue. Suspendisse potenti. Donec porta consectetur tortor, imperdiet tempor nibh ullamcorper ac. In scelerisque convallis magna, consequat tincidunt magna lobortis id.

        Donec vel commodo mi, vitae tincidunt nibh. Mauris a tempus ante, a lobortis est. Fusce sed auctor libero. Donec euismod, urna at semper tincidunt, nisi leo dignissim ex, ut accumsan lorem metus at mi. Cras eu mollis mi. Nunc nulla purus, pulvinar ac porta feugiat, tincidunt nec erat. Curabitur in lacus lobortis, sodales urna vel, ultricies justo. Nulla ultricies id orci condimentum congue. Phasellus feugiat metus metus, quis mollis quam rhoncus non. Nullam tincidunt, ex vel dignissim lobortis, odio leo mollis magna, non lacinia augue dolor et dui. Proin sollicitudin feugiat turpis, sit amet feugiat lectus vehicula sed.

        Proin tincidunt magna id ex interdum, sed vehicula massa ultricies. Aenean ornare elit ligula, et sagittis diam pellentesque id. Suspendisse et sodales ante, id elementum nisl. Donec accumsan tempor dictum. Phasellus eu fringilla diam. Proin non magna felis. Fusce ornare placerat dolor, id congue odio sodales eu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus sit amet tortor sit amet nisl lacinia tempor vitae a ante. Maecenas vel iaculis lacus, et semper nunc. Nunc vel fermentum ipsum. Etiam vitae rhoncus tortor. Nullam venenatis laoreet augue eu pulvinar. Curabitur porttitor sapien at tortor convallis molestie. Duis nec orci lorem.

        Fusce et purus sed massa condimentum porta. Cras in lobortis elit. Nulla facilisi. Fusce egestas tellus sed turpis volutpat, vel tempor lectus blandit. Suspendisse vitae sapien eros. Cras ut laoreet dui. Nunc volutpat porta ante.

        Phasellus cursus metus eu finibus faucibus. Quisque eu ultrices quam. Mauris in sem erat. Suspendisse ac nisi at mi dignissim rhoncus a ac sapien. Ut sed elit nibh. Donec ac laoreet erat, vel cursus diam. Curabitur quis est a diam lobortis posuere.

        Praesent feugiat risus non neque mollis, blandit venenatis libero aliquam. Maecenas dapibus volutpat bibendum. Proin eu nisl nulla. Vivamus porttitor non dui quis pellentesque. Nullam aliquam faucibus ex vel blandit. Morbi non velit sed arcu cursus pretium sit amet at ipsum. Morbi laoreet consectetur erat sed pellentesque. Duis posuere diam et justo congue congue. Nam feugiat rutrum dui vitae rhoncus. Aliquam consectetur justo felis, eget rhoncus erat hendrerit quis.

        Ut non ante a mauris sodales porta. Nunc vel nisl nisi. Donec arcu purus, gravida eu tellus non, tincidunt efficitur augue. Proin maximus tellus et mattis semper. Phasellus odio elit, tempus ac congue at, blandit eu libero. Aenean hendrerit id enim quis volutpat. Vivamus justo turpis, ornare sit amet lorem quis, tincidunt lobortis elit. Praesent maximus orci et pretium condimentum. Aliquam tincidunt, sem a tristique bibendum, nunc tellus porttitor ipsum, vitae porta augue augue nec erat. Nulla id pellentesque eros. Aenean in nisl ut lorem dignissim auctor et in libero. Pellentesque vestibulum commodo felis quis eleifend. Morbi facilisis, nulla sed laoreet pulvinar, mauris erat dapibus velit, sed vestibulum est urna nec erat. Pellentesque id molestie est, at cursus arcu. Integer et erat molestie, venenatis lorem convallis, malesuada sapien. </div>
    )
}

export default About